Metatavu/kunta-api-www-mantyharju

scss/_fonts.scss, scss/_vars.scss
=> Changed heading font

public/js/common.js, scss/contents-common.scss, scss/contents.scss, views/pages/contents.pug
=> Fixed root page header and page menu

routes/common/index.js
=> Changed processPageContent to set content image sizes

routes/search/index.js, views/ajax/search.pug
=> Fixed missing first result parameter

views/pages/announcement.pug
=> Added missing announcement page

routes/common-data/index.js, scss/index.scss, views/pages/index.pug
=> Feature #18 tile second index

scss/event.scss, views/includes/mixins.pug, views/pages/event.pug
=> Fixed menu in event page

public/.gitignore, routes/root/index.js, scss/styles.scss, views/pages/index.pug
=> Added carousel for movies

routes/root/index.js, views/pages/index.pug
=> Check if background color is not given

views/pages/index.pug
=> Feature #37 front oage links

routes/common-data/index.js, scss/index.scss, views/includes/footer.pug, views/pages/index.pug
=> Feature #40 some

public/js/common.js, routes/root/index.js, views/pages/index.pug
=> Hotfix #43 movie banners

public/js/contents.js, routes/pages/index.js, scss/contents-common.scss, scss/contents.scss, views/fragments/movie.pug, views/pages/contents.pug
=> Hotfix #46 movie description

routes/common/index.js, routes/pages/index.js, routes/root/index.js, views/error/404.pug, views/error/500.pug, views/fragments/movie.pug, views/pages/index.pug
=> Feature #59 movie showtimes

public/gfx/layout/mantyharju_logo_desktop.svg, public/gfx/layout/mantyharju_logo_mobile.svg
=> Removed width and height attributes from svg logos

scss/index.scss
=> Fixed quick nav icons on ie

routes/common/index.js, views/fragments/movie.pug
=> Feature #72 movie director and cast

.gitignore, index.js, package.json, public/js/metaform-extensions.js, routes/common/index.js, routes/events/forms/create-event.json, routes/events/index.js, scss/metaform.scss, views/includes/mixins.pug, views/pages/event-new.pug, views/pages/events-list.pug
=> Feature #75 linkedevents form

package.json, public/js/event-new.js, routes/events/forms/create-event.json, routes/events/forms/create-place.json, routes/events/index.js, scss/metaform.scss, views/ajax/place-new.pug, views/pages/event-new.pug
=> Feature #84 add event locations

routes/index.js, routes/shortlinks/index.js
=> Added support for shortlinks

routes/common/index.js, routes/events/forms/create-event.json, routes/events/index.js
=> Review changes

public/js/event-new.js, routes/events/index.js
=> Changed events to be created as drafts

routes/common-data/index.js, routes/incidents/index.js, routes/index.js, views/includes/head.pug
=> Added incidents module

scss/_colors.scss, scss/announcements-list.scss, views/pages/announcements-list.pug
=> Hotfix #104 announcements listing

views/pages/event.pug
=> Added event location info

routes/events/index.js
=> Added minutes to event template

routes/events/index.js
=> Added server side validations for new event name and location

scss/index.scss, views/pages/index.pug
=> Added new tile to front page

package-lock.json, package.json
=> Updated metaform fields

package-lock.json, package.json, routes/events/index.js
=> Added better error messaege for malformed event url

routes/events/index.js
=> Added more validation for event creation dates

views/pages/index.pug
=> Support html encoded entities in news and annoucement and event titles

views/pages/index.pug
=> Events link to events page

views/pages/index.pug
=> Feature #139 events link

scss/index.scss, views/pages/index.pug
=> Feature #141 static event

routes/common/index.js, scss/index.scss, views/pages/index.pug
=> Feature #145 events limit

routes/common/index.js, routes/events/forms/create-event.json, routes/events/index.js, scss/index.scss, views/pages/index.pug
=> Feature #147 end date required

routes/common/index.js, routes/events/forms/create-event.json, routes/events/index.js, routes/root/index.js, scss/index.scss, views/pages/index.pug
=> Feature #149 show events by endtime

routes/events/index.js
=> fixed date filter parameters

public/js/jobs.js, routes/index.js, routes/jobs/index.js, scss/jobs.scss, views/pages/contents.pug
=> Added possibility to add list of jobs

routes/events/index.js
=> Improved event date display

routes/common/index.js, routes/search/index.js, views/ajax/search.pug
=> Improved search

package-lock.json, scss/index.scss, scss/jobs.scss, views/includes/head.pug, views/pages/contents.pug
=> Index for joblist

package-lock.json, views/pages/index.pug
=> Hotfix #179 banner bug

package-lock.json, scss/index.scss, views/pages/index.pug
=> Added full size link

routes/common-data/index.js, views/includes/head.pug
=> Added alert for cookies

routes/common/index.js, views/pages/index.pug
=> Enhanced error handling on index page

views/includes/head.pug
=> Support chaging cookie info linkmsg

scss/index.scss
=> Fixed banner bug

package-lock.json, views/ajax/events-list.pug
=> Fixed event list bug

scss/index.scss
=> Forced text to white

package-lock.json, package.json, routes/events/index.js
=> Changed newlines to p tags and used autolinker to create links

package-lock.json, routes/root/index.js
=> Changed events filter

routes/events/index.js, routes/root/index.js, views/pages/index.pug
=> front page event list divide

routes/root/index.js
=> fix index page event list

.eslintrc.json, .hound.yml, package-lock.json, package.json, routes/events/index.js, views/includes/mixins.pug
=> Feature 219 change events to be read directly from linkedevents api

public/js/event-new.js, routes/events/forms/create-event.json
=> Change event form to view only selected localized values

package-lock.json, package.json, public/js/event-new.js, routes/events/forms/create-event.json, routes/events/index.js, scss/event-new.scss, views/pages/event-new.pug
=> Feature 228 default event images

views/pages/news-article.pug
=> Added lazy loader to news article

.hound.yml, .scss-style.yml, routes/events/forms/create-event.json, scss/metaform.scss
=> Added form layout and help containers

routes/events/forms/create-event.json
=> Form layout upgrade

routes/events/forms/create-event.json, scss/metaform.scss
=> Added keywords and css

routes/events/forms/create-event.json
=> Changes to help containers pointed out by customer

routes/events/index.js
=> Hotfix 253 added isarray

routes/common/index.js, routes/events/index.js, routes/root/index.js
Fixed all incoming not showing in front page
Resolve #258
=> Incoming events fixed in front page

routes/events/index.js, views/pages/event.pug
Price and place can be see at event page
Resolve #261
=> Price and place can be see at event page

routes/events/forms/create-event.json, routes/events/index.js
=> Hotfix 264 user uploads

package-lock.json, package.json, routes/common/index.js, routes/events/forms/create-event.json, routes/events/index.js
=> Hotfix 267 event image upload
